# Generated by Django 3.0.5 on 2020-05-04 00:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import load_files.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FileType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_type', models.CharField(max_length=400, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=load_files.models.file_directory_path, verbose_name='data_file')),
                ('filename', models.CharField(max_length=400, null=True)),
                ('file_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='files', to='load_files.FileType')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='files', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
