# Generated by Django 2.2.12 on 2020-05-04 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('load_files', '0002_auto_20200504_1558'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filetype',
            name='image_path',
            field=models.CharField(max_length=1000),
        ),
    ]
